"""Pydantic models for recommendation engine request/response contracts.

Consumed by: rules engine, Claude API layer, hybrid orchestrator, API routes.
"""

from pydantic import BaseModel, Field, field_validator, model_validator


VALID_PLAYSTYLES: dict[int, set[str]] = {
    1: {"Farm-first", "Aggressive", "Split-push", "Fighting"},
    2: {"Tempo", "Ganker", "Greedy", "Space-maker"},
    3: {"Frontline", "Aura-carrier", "Initiator", "Greedy"},
    4: {"Roamer", "Lane-dominator", "Greedy", "Save"},
    5: {"Lane-protector", "Roamer", "Greedy", "Save"},
}


class EnemyContext(BaseModel):
    """Per-enemy hero context from screenshot parsing (KDA + level)."""

    hero_id: int
    kills: int | None = None
    deaths: int | None = None
    assists: int | None = None
    level: int | None = None


class RecommendRequest(BaseModel):
    """POST /api/recommend request body."""

    hero_id: int
    role: int = Field(ge=1, le=5)  # Pos 1-5
    playstyle: str
    side: str  # "radiant" | "dire"
    lane: str  # "safe" | "off" | "mid"
    lane_opponents: list[int] = Field(default_factory=list, max_length=2)
    allies: list[int] = Field(default_factory=list, max_length=4)
    # all_opponents: full 5-hero enemy team for win condition classification.
    # lane_opponents: max 2 heroes for matchup data and counter-item rules (separate concern).
    all_opponents: list[int] = Field(default_factory=list, max_length=5)

    # Mid-game adaptation fields (all optional for backward compatibility)
    lane_result: str | None = None  # "won" | "even" | "lost"
    damage_profile: dict[str, int] | None = None  # e.g. {"physical": 60, "magical": 30, "pure": 10}
    enemy_items_spotted: list[str] = Field(default_factory=list)  # e.g. ["bkb", "blink"]
    purchased_items: list[int] = Field(default_factory=list)  # item_ids already purchased
    enemy_context: list[EnemyContext] = Field(default_factory=list)

    # Engine mode override (Phase 26): "fast" | "auto" | "deep" | None (uses settings default)
    mode: str | None = None

    # Game clock for time-aware reasoning (Phase 36: PROM-02)
    game_time_seconds: int | None = None  # from GSI clock; None = unknown/pre-game

    # Turbo mode flag (Phase 36: PROM-05) -- halves all timing benchmarks
    turbo: bool = False

    @field_validator("playstyle")
    @classmethod
    def validate_playstyle(cls, v: str, info) -> str:
        """Reject playstyle that doesn't match the selected role."""
        role = info.data.get("role")
        if role is not None and v not in VALID_PLAYSTYLES.get(role, set()):
            valid_options = ", ".join(sorted(VALID_PLAYSTYLES.get(role, set())))
            raise ValueError(
                f"Playstyle '{v}' is not valid for role {role}. Valid options: {valid_options}"
            )
        return v

    @model_validator(mode="after")
    def validate_damage_profile_sum(self) -> "RecommendRequest":
        """Reject damage profiles that don't sum to 100%."""
        if self.damage_profile is not None:
            total = sum(self.damage_profile.values())
            if total != 100:
                raise ValueError(
                    f"Damage profile must sum to 100%, got {total}%"
                )
        return self


class RuleResult(BaseModel):
    """Output of a single deterministic rule evaluation."""

    item_id: int
    item_name: str
    reasoning: str
    phase: str  # "starting" | "laning" | "core" | "late_game"
    priority: str  # "core" | "situational" | "luxury"
    counter_target: str | None = None  # e.g. "Witch Doctor: Death Ward (channeled)"


def compute_threat_level(ec: EnemyContext) -> str:
    """Classify enemy threat: 'high', 'normal', 'behind'.

    Matches context_builder._build_enemy_context_section logic:
    - fed/high threat: kills >= 5 and K/D >= 2 (or deaths == 0)
    - behind: deaths >= 3 and D/K >= 2 (or kills == 0)
    - normal: everything else
    """
    k = ec.kills or 0
    d = ec.deaths or 0
    if (k >= 5 and d > 0 and k >= 2 * d) or (k >= 5 and d == 0):
        return "high"
    elif (d >= 3 and k > 0 and d >= 2 * k) or (d >= 3 and k == 0):
        return "behind"
    return "normal"


class ComponentStep(BaseModel):
    """Single component in a build path order.

    Pre-computed by _enrich_build_paths -- costs from DataCache, NOT from Claude.
    reason is either from Claude's build_path_notes or a heuristic fallback string.
    """
    item_name: str          # internal_name (e.g. "ogre_axe") for image URL resolution
    item_id: int            # for DataCache lookup; 0 if component not in cache
    cost: int | None        # from DataCache.get_item(item_id).cost; None if unknown
    reason: str             # why this component is bought at this position
    position: int           # 1-based purchase order index


class BuildPathResponse(BaseModel):
    """Component purchase order for a single recommended item.

    Pre-computed post-LLM in _enrich_build_paths -- NOT generated by Claude directly.
    Ordering: Claude's component_order if present and valid; else heuristic fallback.
    Only generated for items with >= 2 components.
    """
    item_name: str                    # matches ItemRecommendation.item_name
    steps: list[ComponentStep]        # ordered from first-buy to last-buy
    build_path_notes: str             # Claude's overall ordering justification paragraph


class WinConditionResponse(BaseModel):
    """Win condition classification for allied and enemy teams.

    Pre-computed by WinConditionClassifier -- NOT generated by Claude.
    Carried on RecommendResponse for frontend badge display.
    """
    allied_archetype: str           # e.g. "teamfight"
    allied_confidence: str          # "high" | "medium" | "low"
    enemy_archetype: str | None = None     # None if enemy team < 3 heroes
    enemy_confidence: str | None = None    # None if enemy team < 3 heroes


class ItemRecommendation(BaseModel):
    """Single item recommendation with reasoning."""

    item_id: int
    item_name: str
    reasoning: str
    priority: str  # "core" | "situational" | "luxury"
    conditions: str | None = None  # For situational decision tree cards
    gold_cost: int | None = None  # Populated from Item.cost during validation
    component_order: list[str] | None = None  # Claude's ordered internal_names; validated in _enrich_build_paths
    build_path_notes: str | None = None       # Claude's overall component ordering reasoning paragraph


class RecommendPhase(BaseModel):
    """A game phase with its recommended items."""

    phase: str  # "starting" | "laning" | "core" | "late_game" | "situational"
    items: list[ItemRecommendation]
    timing: str | None = None
    gold_budget: int | str | None = None  # Claude sometimes returns "unlimited"


class NeutralItemPick(BaseModel):
    """Single neutral item recommendation with reasoning."""

    item_name: str
    reasoning: str
    rank: int


class NeutralTierRecommendation(BaseModel):
    """Neutral item recommendations for a single tier."""

    tier: int
    items: list[NeutralItemPick]

    @field_validator("tier", mode="before")
    @classmethod
    def parse_tier(cls, v: int | str) -> int:
        """Accept 'T1', 'T2', etc. and convert to integer."""
        if isinstance(v, str):
            return int(v.replace("T", "").replace("t", "").strip())
        return v


class LLMRecommendation(BaseModel):
    """Schema for Claude structured output. Used to generate JSON schema for output_config."""

    phases: list[RecommendPhase]
    overall_strategy: str
    neutral_items: list[NeutralTierRecommendation] = Field(default_factory=list)


class ItemTimingResponse(BaseModel):
    """Per-item timing benchmark data for frontend display.

    Pre-computed by the recommender's _enrich_timing_data step (post-LLM).
    NOT generated by Claude -- timing data is population-level statistics
    from OpenDota, enriched from DataCache.
    """

    item_name: str                    # internal_name (matches ItemRecommendation.item_name)
    buckets: list[dict]               # [{time, games, win_rate, confidence, zone}, ...]
    is_urgent: bool                   # Steep win-rate falloff detected
    good_range: str                   # "< 20 min" (pre-formatted)
    ontrack_range: str                # "20-25 min"
    late_range: str                   # "> 25 min"
    good_win_rate: float              # 0-1 float
    ontrack_win_rate: float           # 0-1 float
    late_win_rate: float              # 0-1 float
    confidence: str                   # "strong" | "moderate" | "weak" (aggregate)
    total_games: int                  # Sample size for tooltip


class RecommendResponse(BaseModel):
    """POST /api/recommend response body."""

    phases: list[RecommendPhase]
    overall_strategy: str | None = None
    neutral_items: list[NeutralTierRecommendation] = Field(default_factory=list)
    timing_data: list[ItemTimingResponse] = Field(default_factory=list)
    build_paths: list[BuildPathResponse] = Field(default_factory=list)
    win_condition: WinConditionResponse | None = None
    win_probability: float | None = None  # 0.0-1.0, allied win probability; None if unavailable
    fallback: bool = False
    fallback_reason: str | None = None  # "timeout" | "parse_error" | "api_error" | "rate_limited"
    model: str | None = None
    latency_ms: int | None = None
    engine_mode: str | None = None  # "fast" | "auto" | "deep"
    budget_used: float | None = None  # Current month's Claude API spend in USD
    budget_limit: float | None = None  # Monthly budget cap in USD


# Hand-crafted inline JSON schema for Anthropic structured output.
# No $ref, no anyOf, no $defs — fully inlined for maximum API compatibility and speed.
LLM_OUTPUT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["phases", "overall_strategy"],
    "properties": {
        "phases": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["phase", "items"],
                "properties": {
                    "phase": {"type": "string"},
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["item_id", "item_name", "reasoning", "priority"],
                            "properties": {
                                "item_id": {"type": "integer"},
                                "item_name": {"type": "string"},
                                "reasoning": {"type": "string"},
                                "priority": {"type": "string"},
                                "conditions": {"type": "string", "nullable": True},
                                "gold_cost": {"type": "integer", "nullable": True},
                                "component_order": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "nullable": True,
                                },
                                "build_path_notes": {"type": "string", "nullable": True},
                            },
                        },
                    },
                    "timing": {"type": "string", "nullable": True},
                    "gold_budget": {"type": "integer", "nullable": True},
                },
            },
        },
        "overall_strategy": {"type": "string"},
        "neutral_items": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["tier", "items"],
                "properties": {
                    "tier": {"type": "integer"},
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["item_name", "reasoning", "rank"],
                            "properties": {
                                "item_name": {"type": "string"},
                                "reasoning": {"type": "string"},
                                "rank": {"type": "integer"},
                            },
                        },
                    },
                },
            },
        },
    },
}


# ---------------------------------------------------------------------------
# Screenshot parsing schemas (Phase 13)
# ---------------------------------------------------------------------------


class VisionItem(BaseModel):
    """Raw item from Vision output before DB matching."""

    name: str
    confidence: str  # "certain" | "likely" | "uncertain"


class VisionHero(BaseModel):
    """Raw hero from Vision output before DB matching."""

    hero_name: str
    team: str | None = None  # "radiant" or "dire"
    items: list[VisionItem] = Field(default_factory=list)
    kills: int | None = None
    deaths: int | None = None
    assists: int | None = None
    level: int | None = None


class VisionResponse(BaseModel):
    """Raw Vision output schema."""

    heroes: list[VisionHero] = Field(default_factory=list)
    error: str | None = None
    message: str | None = None


class ParsedItem(BaseModel):
    """Single item after DB matching."""

    display_name: str
    internal_name: str
    confidence: str  # "high" | "medium" | "low"


class ParsedHero(BaseModel):
    """Single hero after DB matching."""

    hero_name: str
    hero_id: int | None = None
    internal_name: str | None = None
    team: str | None = None  # "radiant" or "dire"
    items: list[ParsedItem] = Field(default_factory=list)
    kills: int | None = None
    deaths: int | None = None
    assists: int | None = None
    level: int | None = None


class ScreenshotParseRequest(BaseModel):
    """POST /api/parse-screenshot request."""

    image_base64: str
    media_type: str = "image/png"


class ScreenshotParseResponse(BaseModel):
    """POST /api/parse-screenshot response."""

    heroes: list[ParsedHero] = Field(default_factory=list)
    error: str | None = None
    message: str | None = None
    latency_ms: int | None = None


# ---------------------------------------------------------------------------
# Hero suggestion schemas (Phase 31)
# ---------------------------------------------------------------------------


class SuggestHeroRequest(BaseModel):
    """POST /api/suggest-hero request body."""

    role: int = Field(ge=1, le=5)
    ally_ids: list[int] = Field(default_factory=list, max_length=4)
    enemy_ids: list[int] = Field(default_factory=list, max_length=5)
    excluded_hero_ids: list[int] = Field(default_factory=list)
    top_n: int = Field(default=10, ge=1, le=30)
    bracket: int = Field(default=2, ge=1, le=4)


class HeroSuggestion(BaseModel):
    """Single ranked hero candidate."""

    hero_id: int
    hero_name: str
    internal_name: str
    icon_url: str | None
    score: float
    synergy_score: float
    counter_score: float


class SuggestHeroResponse(BaseModel):
    """POST /api/suggest-hero response body."""

    suggestions: list[HeroSuggestion]
    matrices_available: bool
